# Generated by Django 5.0 on 2025-06-09 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('client', 'Клиент'), ('master', 'Мастер'), ('admin', 'Администратор')], default='client', max_length=20, verbose_name='Роль'),
        ),
    ]
