# Generated by Django 5.0 on 2025-06-09 06:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_user_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=19, validators=[django.core.validators.RegexValidator(message="Номер телефона должен быть в формате: '+7 (999) 999-99-99'", regex='^\\+7 \\(\\d{3}\\) \\d{3}-\\d{2}-\\d{2}$')]),
        ),
    ]
