# Generated by Django 5.0 on 2025-06-09 05:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='master',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активен'),
        ),
        migrations.AddField(
            model_name='master',
            name='schedule_end',
            field=models.TimeField(default='18:00', verbose_name='Конец рабочего дня'),
        ),
        migrations.AddField(
            model_name='master',
            name='schedule_start',
            field=models.TimeField(default='09:00', verbose_name='Начало рабочего дня'),
        ),
        migrations.AddField(
            model_name='master',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
